# Generated by Django 6.0.5 on 2026-05-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('experience', models.IntegerField(verbose_name='Стаж (лет)')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('photo', models.ImageField(upload_to='masters/')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Рейтинг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('services', models.ManyToManyField(related_name='masters', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('is_working', models.BooleanField(default=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='masters.master')),
            ],
        ),
    ]
