# Generated by Django 6.0.5 on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="master",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="masters/"),
        ),
    ]
